apiVersion: v1
kind: Service
metadata:
  name:  '{{name}}' 
  namespace: '{{docker_namespace}}'
spec:
  selector:
    app: registry
  ports:
    - name: reg
      port: 5000
      targetPort: 5000
  externalIPs:
     - '{{docker_ip}}'

