ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|

  config.vm.box_url = "https://dl.rockylinux.org/vault/rocky/9.2/images/x86_64/Rocky-9-Vagrant-Libvirt-9.2-20230513.0.x86_64.box"
  config.vm.box = "Rocky-9-Vagrant-Libvirt-9.2-20230513.0.x86_64.box"
  config.vm.box_download_checksum = "a962dc2ce0b0ae1c1cc69c093edb1fc0c843262c38d206d3fcaa84564de7579c"
  config.vm.box_download_checksum_type = "sha256"

  config.vm.synced_folder ".", "/vagrant",  disabled: true  #type: "virtiofs"

  config.vm.define "master-vagrant" do |app1|
    
    app1.vm.hostname = "master-vagrant"
    app1.vm.network :private_network,   ip: "10.54.56.121" ,
        libvirt__network_name: "bridge-kvm"
    
    app1.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 4096
      libvirt.keymap= "fr"
    end

  end

  config.vm.define "node-vagrant" do |app1|
    
    app1.vm.hostname = "node-vagrant"
    app1.vm.network :private_network,   ip: "10.54.56.122" ,
        libvirt__network_name: "bridge-kvm"
    
    app1.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 4096
      libvirt.keymap= "fr"
    end

  end



end
