---
# tasks file for docker-registery
# implemente la procedure decrite a:
# https://medium.com/swlh/deploy-your-private-docker-registry-as-a-pod-in-kubernetes-f6a489bf0180

- name: create namespace
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'namespace.yaml' ) | from_yaml }}" 

  
- name: 'storage class {{item}}'
  vars: 
      name: '{{item}}-storage-class'
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'storage-class.yaml') | from_yaml }}" 
  loop:
      - registry
      - docker

- name: 'persistence volume {{item}}'
  vars:
    name: '{{item}}-persitence-volume'
    name_storage_class: '{{item}}-storage-class'
    affinity: '{{persitence_node}}'
    path: '/data/docker-registry/{{item}}'
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'PersistentVolume.yaml') | from_yaml }}" 
  loop:
      - registry
      - docker

- name : 'PersistentVolumeClaim {{item}}'
  vars:
    name: '{{item}}-persitence-volume-claim'
    name_storage_class: '{{item}}-storage-class'
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'PersistentVolumeClaim.yaml') | from_yaml }}"
  loop:
    - registry
    - docker
  
- name: service 
  vars:
    name: 'service-{{docker_namespace}}'
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'service.yaml') | from_yaml }}" 
  loop:
    - registry
    - docker

- name: deploy pods
  vars:
    name: 'deployement-{{docker_namespace}}'
    claim_name_registry: 'registry-persitence-volume-claim'
    claim_name_docker: 'docker-persitence-volume-claim'
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'deployment.yaml' ) | from_yaml }}" 



  