version: 0.1
loglevel: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry 
  delete:
    enabled: true
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/htpasswd
http:
  addr: :5000
  secret: 1234
  tls:
    certificate: /etc/docker/certs/tls.crt
    key: /etc/docker/certs/tls.key
